'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Actas
    Public Property IdActas As Integer
    Public Property IdEmpresa As Nullable(Of Integer)
    Public Property Fecha As Nullable(Of Date)
    Public Property Desde As Nullable(Of Date)
    Public Property Hasta As Nullable(Of Date)
    Public Property Importe_Adeudado As Nullable(Of Decimal)
    Public Property Importe_Actualizado As Nullable(Of Decimal)
    Public Property Cuotas As Nullable(Of Integer)
    Public Property Valor_Cuota As Nullable(Of Decimal)
    Public Property Prox_Vencimiento As Nullable(Of Date)
    Public Property Estado As Nullable(Of Boolean)

    Public Overridable Property Empresas As Empresas

End Class
