//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindicato_Viedma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actas
    {
        public int IdActas { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Desde { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
        public Nullable<decimal> Importe_Adeudado { get; set; }
        public Nullable<decimal> Importe_Actualizado { get; set; }
        public Nullable<int> Cuotas { get; set; }
        public Nullable<decimal> Valor_Cuota { get; set; }
        public Nullable<System.DateTime> Prox_Vencimiento { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Empresas Empresas { get; set; }
    }
}
