//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindicato_Viedma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afiliados_Empresa
    {
        public int Id { get; set; }
        public int Id_Afiliado { get; set; }
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }
        public string Nombre_Empresa { get; set; }
        public string Nombre_Fantasia { get; set; }
        public string Cuit_Empresa { get; set; }
        public string Calle { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Piso { get; set; }
        public string Dto { get; set; }
        public Nullable<int> Localidad { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public Nullable<int> Rubro { get; set; }
        public string OtroRubro { get; set; }
    }
}
