//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindicato_Viedma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afiliados_Familiares
    {
        public int Id { get; set; }
        public int Id_Afiliado { get; set; }
        public string Parentesco { get; set; }
        public string Apellido_Nombre { get; set; }
        public Nullable<System.DateTime> Cert_Estudios { get; set; }
        public string Tipo_Doc { get; set; }
        public string Num_Doc { get; set; }
        public Nullable<int> Sexo { get; set; }
        public Nullable<System.DateTime> Fecha_Nac { get; set; }
    }
}
