//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindicato_Viedma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boletas_DDJJ
    {
        public int IdBoletaDDJJ { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<System.DateTime> Periodo_DDJJ { get; set; }
        public Nullable<decimal> Remunerativo { get; set; }
        public Nullable<decimal> No_Remunerativo { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> A_Cuenta { get; set; }
        public Nullable<decimal> Interes_Mora { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Empresas Empresas { get; set; }
    }
}
