'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Boletas_DDJJ
    Public Property IdBoletaDDJJ As Integer
    Public Property IdEmpresa As Nullable(Of Integer)
    Public Property Periodo_DDJJ As Nullable(Of Date)
    Public Property Remunerativo As Nullable(Of Decimal)
    Public Property No_Remunerativo As Nullable(Of Decimal)
    Public Property Importe As Nullable(Of Decimal)
    Public Property A_Cuenta As Nullable(Of Decimal)
    Public Property Interes_Mora As Nullable(Of Decimal)
    Public Property Total As Nullable(Of Decimal)

    Public Overridable Property Empresas As Empresas

End Class
