'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Categorias
    Public Property IdCategoria As Integer
    Public Property NombreCategoria As String

    Public Overridable Property Empleados As ICollection(Of Empleados) = New HashSet(Of Empleados)
    Public Overridable Property SubCategoria As ICollection(Of SubCategoria) = New HashSet(Of SubCategoria)

End Class
