'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleados
    Public Property IdEmpleado As Integer
    Public Property IdEmpresa As Integer
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property TipoDoc As Integer
    Public Property CUIL As String
    Public Property Sexo As String
    Public Property Fecha_Nacimiento As Nullable(Of Date)
    Public Property IdCategoria As Nullable(Of Integer)
    Public Property IdSubcategoria As Nullable(Of Integer)
    Public Property Fecha_Ingreso As Nullable(Of Date)
    Public Property Remuneracion As Nullable(Of Decimal)
    Public Property Suma_No_Remuneracion As Nullable(Of Decimal)
    Public Property Afiliado As Nullable(Of Boolean)
    Public Property IdEstado As Nullable(Of Integer)
    Public Property Activo As Nullable(Of Boolean)
    Public Property Fecha_Baja As String

    Public Overridable Property Categorias As Categorias
    Public Overridable Property Empresas As Empresas
    Public Overridable Property Estados As Estados
    Public Overridable Property TipoDocumentos As TipoDocumentos

End Class
