//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindicato_Viedma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas_Titulares
    {
        public int Id { get; set; }
        public string ApellidoNombre { get; set; }
        public string DomicilioParticular { get; set; }
        public string Documento { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    }
}
