//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindicato_Viedma.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class geosoftw_seocapreinscripcionesEntities : DbContext
    {
        public geosoftw_seocapreinscripcionesEntities()
            : base("name=geosoftw_seocapreinscripcionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afiliados_Empresa> Afiliados_Empresa { get; set; }
        public virtual DbSet<Empresas_Actividades> Empresas_Actividades { get; set; }
        public virtual DbSet<Empresas_Antecedentes> Empresas_Antecedentes { get; set; }
        public virtual DbSet<Empresas_Contadores> Empresas_Contadores { get; set; }
        public virtual DbSet<Empresas_Empleados> Empresas_Empleados { get; set; }
        public virtual DbSet<Empresas_Sucursales> Empresas_Sucursales { get; set; }
        public virtual DbSet<General_Calificacion> General_Calificacion { get; set; }
        public virtual DbSet<General_Delegacion> General_Delegacion { get; set; }
        public virtual DbSet<General_Documentos> General_Documentos { get; set; }
        public virtual DbSet<General_Estado_Civil> General_Estado_Civil { get; set; }
        public virtual DbSet<General_Localidades> General_Localidades { get; set; }
        public virtual DbSet<General_Nacionalidades> General_Nacionalidades { get; set; }
        public virtual DbSet<General_Parentesco> General_Parentesco { get; set; }
        public virtual DbSet<General_Provincias> General_Provincias { get; set; }
        public virtual DbSet<General_Sexo> General_Sexo { get; set; }
        public virtual DbSet<General_Delegacion_Usuarios> General_Delegacion_Usuarios { get; set; }
        public virtual DbSet<General_ActividadRubro> General_ActividadRubro { get; set; }
        public virtual DbSet<Afiliados_Familiares> Afiliados_Familiares { get; set; }
        public virtual DbSet<Afiliados_DatosPersonales> Afiliados_DatosPersonales { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Empresas_Titulares> Empresas_Titulares { get; set; }
    
        public virtual int SP_crearReporteAfiliados(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_crearReporteAfiliados", codigoParameter);
        }
    }
}
