'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empresas
    Public Property IdEmpresa As Integer
    Public Property CUIT As String
    Public Property Sucursal As Integer
    Public Property Cuenta As Nullable(Of Integer)
    Public Property Password As String
    Public Property RazonSocial As String
    Public Property NombreFantasia As String
    Public Property Domicilio As String
    Public Property Provincia As String
    Public Property Localidad As String
    Public Property CP As Nullable(Of Integer)
    Public Property Telefono As String
    Public Property Contacto As String
    Public Property Email As String
    Public Property HorarioAtencion As String
    Public Property Comentario As String

    Public Overridable Property Actas As ICollection(Of Actas) = New HashSet(Of Actas)
    Public Overridable Property Boletas_Actas As ICollection(Of Boletas_Actas) = New HashSet(Of Boletas_Actas)
    Public Overridable Property Boletas_DDJJ As ICollection(Of Boletas_DDJJ) = New HashSet(Of Boletas_DDJJ)
    Public Overridable Property Empleados As ICollection(Of Empleados) = New HashSet(Of Empleados)
    Public Overridable Property Liquidacion As ICollection(Of Liquidacion) = New HashSet(Of Liquidacion)

End Class
