'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LiquidacionPorcentaje
    Public Property IdLiquidacion As Integer
    Public Property Convenio_Colectivo As Nullable(Of Integer)
    Public Property Cuota_Sindical As Nullable(Of Integer)

End Class
