'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class geosoftw_Sindicato_ViedmaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=geosoftw_Sindicato_ViedmaEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Actas() As DbSet(Of Actas)
    Public Overridable Property Boletas_Actas() As DbSet(Of Boletas_Actas)
    Public Overridable Property Boletas_DDJJ() As DbSet(Of Boletas_DDJJ)
    Public Overridable Property Categorias() As DbSet(Of Categorias)
    Public Overridable Property Empleados() As DbSet(Of Empleados)
    Public Overridable Property Empresas() As DbSet(Of Empresas)
    Public Overridable Property Estados() As DbSet(Of Estados)
    Public Overridable Property Liquidacion() As DbSet(Of Liquidacion)
    Public Overridable Property LiquidacionPorcentaje() As DbSet(Of LiquidacionPorcentaje)
    Public Overridable Property SubCategoria() As DbSet(Of SubCategoria)
    Public Overridable Property TipoDocumentos() As DbSet(Of TipoDocumentos)
    Public Overridable Property Vencimiento_Liquidacion() As DbSet(Of Vencimiento_Liquidacion)

End Class
