'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SubCategoria
    Public Property IdSubcategoria As Integer
    Public Property IdCategoria As Nullable(Of Integer)
    Public Property NombreSubcategoria As String

    Public Overridable Property Categorias As Categorias

End Class
